site_name: Human Brain Cell Atlas v1.0
theme:
    name: bootstrap4
    next_previous: true
repo_url: https://github.com/brain-bican/human-brain-cell-atlas_v1_non-neuronal
docs_dir: docs

plugins:
    - bootstrap4-blockquotes
    - bootstrap4-tables